[mcp_servers.supabase]
command = "npx"
args = [
    "-y",
    "@supabase/mcp-server-supabase@latest",
    "--project-ref=qxcchymwswontqcwqogm",
]
env_vars = ["SUPABASE_ACCESS_TOKEN"]

[mcp_servers.supabase.tools.apply_migration]
approval_mode = "approve"

[mcp_servers.supabase.tools.execute_sql]
approval_mode = "approve"
