import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, BriefcaseBusiness, History, Loader2, Mail, Pencil, Percent, Phone, UserRound } from 'lucide-react';
import { PageHeader } from '@/components/shared/PageHeader';
import { useEmployeeDetails, useEmployees } from '@/hooks/usePeople';
import { AdministrativeNotice } from './components/AdministrativeNotice';
import { EmployeeModal } from './components/EmployeeModal';
import { CommissionStatusBadge, EmployeeAvatar, EmployeeStatusBadge, FieldValue } from './components/PeoplePrimitives';
import { AUDIT_EVENT_LABELS, EMPLOYMENT_TYPE_LABELS, formatCurrency, formatDate, formatReferencePeriod } from './peopleDomain';

type Tab = 'overview' | 'professional' | 'commissions' | 'history';
const tabs: { key: Tab; label: string; icon: typeof UserRound }[] = [{ key: 'overview', label: 'Visão geral', icon: UserRound }, { key: 'professional', label: 'Dados profissionais', icon: BriefcaseBusiness }, { key: 'commissions', label: 'Comissões', icon: Percent }, { key: 'history', label: 'Histórico', icon: History }];

export const EmployeeDetailPage = () => {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [tab, setTab] = useState<Tab>('overview'); const [editing, setEditing] = useState(false);
  const { employee, commissions, audit } = useEmployeeDetails(id); const { employees, saveEmployee, isSaving } = useEmployees({});
  if (employee.isLoading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-700" /></div>;
  if (employee.isError || !employee.data) return <div role="alert" className="rounded-2xl border border-red-100 bg-white p-10 text-center dark:border-red-500/15 dark:bg-[#1a1d27]"><h1 className="font-bold text-gray-900 dark:text-white">Funcionário não encontrado.</h1><button type="button" onClick={() => navigate('/pessoas/funcionarios')} className="mt-4 text-sm font-semibold text-cyan-700">Voltar para funcionários</button></div>;
  const person = employee.data; const records = commissions.data || []; const events = audit.data || [];
  const relatedMembers = person.teamId ? employees.filter((member) => member.teamId === person.teamId && member.id !== person.id) : [];
  return <div className="space-y-5 animate-fade-in"><button type="button" onClick={() => navigate('/pessoas/funcionarios')} className="inline-flex items-center gap-2 text-sm font-semibold text-gray-500 hover:text-cyan-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500"><ArrowLeft className="h-4 w-4" />Funcionários</button><PageHeader title={person.fullName} subtitle={`${person.jobTitle}${person.department ? ` · ${person.department}` : ''}`} action={<button type="button" onClick={() => setEditing(true)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-800"><Pencil className="h-4 w-4" />Editar funcionário</button>} /><AdministrativeNotice />
    <section className="flex flex-col gap-4 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27] sm:flex-row sm:items-center"><EmployeeAvatar name={person.fullName} size="lg" /><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-gray-900 dark:text-white">{person.fullName}</h2><EmployeeStatusBadge status={person.status} /></div><p className="mt-1 text-sm text-gray-500">{EMPLOYMENT_TYPE_LABELS[person.employmentType]} · Admissão: {formatDate(person.admissionDate)}</p></div></section>
    <nav aria-label="Seções do perfil" className="flex overflow-x-auto border-b border-gray-200 dark:border-white/10">{tabs.map((item) => <button key={item.key} type="button" onClick={() => setTab(item.key)} className={`inline-flex items-center gap-2 whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500 ${tab === item.key ? 'border-cyan-700 text-cyan-700 dark:text-cyan-300' : 'border-transparent text-gray-500 hover:text-gray-900 dark:hover:text-white'}`}><item.icon className="h-4 w-4" />{item.label}</button>)}</nav>
    {tab === 'overview' && <div className="grid grid-cols-1 gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27] lg:col-span-2"><h3 className="mb-4 text-sm font-bold text-gray-900 dark:text-white">Resumo</h3><dl className="grid grid-cols-1 gap-5 sm:grid-cols-2"><FieldValue label="Cargo">{person.jobTitle}</FieldValue><FieldValue label="Setor">{person.department}</FieldValue><FieldValue label="Vínculo">{EMPLOYMENT_TYPE_LABELS[person.employmentType]}</FieldValue><FieldValue label="Comissão">{person.commissionEnabled ? 'Participa' : 'Não participa'}</FieldValue><div className="sm:col-span-2"><FieldValue label="Observações internas">{person.internalNotes}</FieldValue></div></dl></section><div className="space-y-5"><section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><h3 className="mb-4 text-sm font-bold text-gray-900 dark:text-white">Contato protegido</h3><div className="space-y-3 text-sm text-gray-600 dark:text-gray-300"><p className="flex items-center gap-2"><Mail className="h-4 w-4 text-gray-400" />{person.email || 'Não informado'}</p><p className="flex items-center gap-2"><Phone className="h-4 w-4 text-gray-400" />{person.phone || 'Não informado'}</p><p className="text-xs text-gray-400">CPF: {person.cpfMasked || 'Não informado'}</p></div></section><section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><h3 className="text-sm font-bold text-gray-900 dark:text-white">Registros de comissão</h3><p className="mt-2 text-3xl font-bold text-cyan-700 dark:text-cyan-300">{records.length}</p><p className="text-xs text-gray-500">Somente registros administrativos vinculados.</p></section></div></div>}
    {tab === 'professional' && <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><dl className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"><FieldValue label="Cargo">{person.jobTitle}</FieldValue><FieldValue label="Setor">{person.department}</FieldValue><FieldValue label="Tipo de vínculo">{EMPLOYMENT_TYPE_LABELS[person.employmentType]}</FieldValue><FieldValue label="Data de admissão">{formatDate(person.admissionDate)}</FieldValue><FieldValue label="Status"><EmployeeStatusBadge status={person.status} /></FieldValue><FieldValue label="Data de nascimento">{formatDate(person.birthDate)}</FieldValue><div className="sm:col-span-2 lg:col-span-3"><FieldValue label="Observação sobre comissão">{person.commissionRuleNotes}</FieldValue></div></dl></section>}
    {tab === 'commissions' && <section className="space-y-3">{commissions.isLoading ? <Loader2 className="h-6 w-6 animate-spin text-cyan-700" /> : records.length === 0 ? <div className="rounded-2xl border border-gray-100 bg-white p-10 text-center text-sm text-gray-500 dark:border-white/5 dark:bg-[#1a1d27]">Nenhum registro de comissão vinculado.</div> : records.map((record) => <article key={record.id} className="grid grid-cols-1 gap-3 rounded-2xl border border-gray-100 bg-white p-4 shadow-sm dark:border-white/5 dark:bg-[#1a1d27] sm:grid-cols-4 sm:items-center"><div className="sm:col-span-2"><h3 className="font-semibold text-gray-900 dark:text-white">{record.description}</h3><p className="text-xs text-gray-500">{formatReferencePeriod(record.referencePeriod)}</p></div><div><CommissionStatusBadge status={record.status} /></div><div className="font-bold text-gray-900 dark:text-white sm:text-right">{formatCurrency(record.grossAmount)}</div></article>)}</section>}
    {tab === 'history' && <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]">{audit.isLoading ? <Loader2 className="h-6 w-6 animate-spin text-cyan-700" /> : events.length === 0 ? <p className="py-8 text-center text-sm text-gray-500">Nenhum evento registrado.</p> : <ol className="space-y-4">{events.map((event) => <li key={event.id} className="relative border-l-2 border-cyan-100 pl-5 dark:border-cyan-400/20"><span className="absolute -left-[5px] top-1 h-2 w-2 rounded-full bg-cyan-600" /><h3 className="text-sm font-semibold text-gray-900 dark:text-white">{AUDIT_EVENT_LABELS[event.eventType] || event.eventType}</h3><p className="mt-1 text-xs text-gray-500">{event.actorName} · {new Date(event.createdAt).toLocaleString('pt-BR')}</p>{event.changedFields.length > 0 && <p className="mt-1 text-[11px] text-gray-400">Campos: {event.changedFields.join(', ')}</p>}</li>)}</ol>}</section>}
    {tab === 'overview' && <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><h3 className="text-sm font-bold text-gray-900 dark:text-white">Equipe e relações</h3><dl className="mt-4 grid grid-cols-1 gap-5 sm:grid-cols-2"><FieldValue label="Equipe / setor">{person.teamName || person.department}</FieldValue><FieldValue label="Gestor responsável">{person.managerName}</FieldValue></dl><div className="mt-5 border-t border-gray-100 pt-4 dark:border-white/5"><h4 className="text-xs font-bold uppercase tracking-wider text-gray-400">Integrantes relacionados</h4>{relatedMembers.length ? <div className="mt-3 flex flex-wrap gap-2">{relatedMembers.map((member) => <button type="button" key={member.id} onClick={() => navigate(`/pessoas/funcionarios/${member.id}`)} className="rounded-full border border-gray-200 px-3 py-1.5 text-xs font-semibold text-gray-700 hover:border-cyan-300 hover:text-cyan-700 focus-visible:ring-2 focus-visible:ring-cyan-500 dark:border-white/10 dark:text-gray-200">{member.fullName}</button>)}</div> : <p className="mt-2 text-sm text-gray-500">Nenhum outro integrante vinculado.</p>}</div></section>}
    <EmployeeModal isOpen={editing} employee={person} employees={employees} isLoading={isSaving} onClose={() => setEditing(false)} onSave={async (input) => { await saveEmployee({ input, id: person.id }); setEditing(false); employee.refetch(); }} />
  </div>;
};
