import { useState } from 'react';
import { AlertTriangle, Ban, CheckCircle2, Pencil, Plus, RefreshCw, Search, Target, TimerOff } from 'lucide-react';
import { DataTable } from '@/components/shared/DataTable';
import { PageHeader } from '@/components/shared/PageHeader';
import { StatCard } from '@/components/shared/StatCard';
import { useEmployees, useSalesGoals, useTeams } from '@/hooks/usePeople';
import { SalesGoal, SalesGoalStatus } from '@/types';
import { isGoalAtRisk } from '@/services/peopleGoalsService';
import { AdministrativeNotice } from './components/AdministrativeNotice';
import { GoalModal } from './components/GoalModal';
import { GoalResultModal } from './components/GoalResultModal';
import { GoalProgress, GoalStatusBadge } from './components/PeoplePrimitives';
import { formatDate, formatGoalValue, SALES_GOAL_TYPE_LABELS } from './peopleDomain';

const fieldClass = 'rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm text-gray-700 outline-none focus-visible:border-cyan-500 focus-visible:ring-2 focus-visible:ring-cyan-500/20 dark:border-white/10 dark:bg-[#1a1d27] dark:text-gray-200';
const yearPeriod = () => { const year = new Date().getFullYear(); return { from: `${year}-01-01`, to: `${year}-12-31` }; };

export const SalesGoalsPage = () => {
  const period = yearPeriod(); const [search, setSearch] = useState(''); const [teamId, setTeamId] = useState(''); const [employeeId, setEmployeeId] = useState(''); const [status, setStatus] = useState<SalesGoalStatus | 'all'>('all'); const [dateFrom, setDateFrom] = useState(period.from); const [dateTo, setDateTo] = useState(period.to);
  const [editing, setEditing] = useState<SalesGoal>(); const [manualGoal, setManualGoal] = useState<SalesGoal>(); const [isOpen, setIsOpen] = useState(false);
  const { teams } = useTeams({}); const { employees } = useEmployees({}); const { goals, isLoading, isError, refetch, saveGoal, isSaving, updateResult, isUpdatingResult, updateStatus } = useSalesGoals({ search, teamId, employeeId, status, dateFrom, dateTo });
  const atRisk = goals.filter((goal) => isGoalAtRisk(goal)); const achieved = goals.filter((goal) => goal.effectiveStatus === 'completed'); const expired = goals.filter((goal) => goal.effectiveStatus === 'expired'); const active = goals.filter((goal) => goal.effectiveStatus === 'active');
  const openCreate = () => { setEditing(undefined); setIsOpen(true); }; const openEdit = (goal: SalesGoal) => { setEditing(goal); setIsOpen(true); };
  const actions = (goal: SalesGoal) => <div className="flex items-center gap-1"><button type="button" onClick={() => openEdit(goal)} disabled={goal.effectiveStatus === 'canceled'} aria-label={`Editar meta ${goal.name}`} className="rounded-lg p-2 text-gray-400 hover:bg-cyan-50 hover:text-cyan-700 disabled:opacity-30 dark:hover:bg-cyan-400/10"><Pencil className="h-4 w-4" /></button>{(goal.resultSource === 'manual' || !goal.hasAutomaticSource) && goal.effectiveStatus === 'active' && <button type="button" onClick={() => setManualGoal(goal)} aria-label={`Atualizar resultado de ${goal.name}`} className="rounded-lg px-2 py-1.5 text-xs font-semibold text-cyan-700 hover:bg-cyan-50 dark:text-cyan-300 dark:hover:bg-cyan-400/10">Resultado</button>}{goal.effectiveStatus === 'active' && <button type="button" onClick={() => updateStatus({ id: goal.id, value: 'canceled' })} aria-label={`Cancelar meta ${goal.name}`} className="rounded-lg p-2 text-gray-400 hover:bg-orange-50 hover:text-orange-600"><Ban className="h-4 w-4" /></button>}</div>;
  const columns = [
    { key: 'name', label: 'Meta', render: (goal: SalesGoal) => <span><span className="block font-semibold text-gray-900 dark:text-white">{goal.name}</span><span className="block text-xs text-gray-400">{SALES_GOAL_TYPE_LABELS[goal.goalType]} · {goal.resultSource === 'automatic' && goal.hasAutomaticSource ? 'Dados reais' : 'Resultado manual'}</span></span> },
    { key: 'owner', label: 'Responsável', render: (goal: SalesGoal) => goal.employeeName || goal.teamName || 'Não disponível' },
    { key: 'period', label: 'Período', render: (goal: SalesGoal) => <span className="text-xs">{formatDate(goal.startDate)}<span className="block text-gray-400">até {formatDate(goal.endDate)}</span></span> },
    { key: 'target', label: 'Objetivo / atual', render: (goal: SalesGoal) => <span className="text-sm"><strong>{formatGoalValue(goal)}</strong><span className="block text-xs text-gray-400">Atual: {formatGoalValue(goal, goal.currentResult)}</span></span> },
    { key: 'progress', label: 'Progresso', render: (goal: SalesGoal) => <GoalProgress value={goal.progressPercent} /> },
    { key: 'status', label: 'Status', render: (goal: SalesGoal) => <GoalStatusBadge status={goal.effectiveStatus} /> },
    { key: 'actions', label: 'Ações', render: actions },
  ];
  return <div className="space-y-5 animate-fade-in"><PageHeader title="Metas de vendas" subtitle="Acompanhe metas individuais e coletivas com resultados reais ou atualização manual." action={<button type="button" onClick={openCreate} disabled={employees.length === 0 && teams.length === 0} className="inline-flex items-center gap-2 rounded-xl bg-cyan-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-800 disabled:opacity-50"><Plus className="h-4 w-4" />Criar meta</button>} /><AdministrativeNotice />
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Metas ativas" value={active.length} icon={<Target className="h-5 w-5" />} accentColor="blue" /><StatCard title="Metas atingidas" value={achieved.length} icon={<CheckCircle2 className="h-5 w-5" />} accentColor="green" /><StatCard title="Metas em risco" value={atRisk.length} icon={<AlertTriangle className="h-5 w-5" />} accentColor="yellow" /><StatCard title="Metas vencidas" value={expired.length} icon={<TimerOff className="h-5 w-5" />} accentColor="red" /></div>
    <section aria-label="Filtros de metas" className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-6"><label className="relative"><span className="sr-only">Buscar metas</span><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Meta ou responsável" className={`${fieldClass} w-full pl-9`} /></label><select value={teamId} onChange={(event) => setTeamId(event.target.value)} aria-label="Filtrar por equipe" className={fieldClass}><option value="">Todas as equipes</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select><select value={employeeId} onChange={(event) => setEmployeeId(event.target.value)} aria-label="Filtrar por funcionário" className={fieldClass}><option value="">Todos os funcionários</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value as SalesGoalStatus | 'all')} aria-label="Filtrar por status" className={fieldClass}><option value="all">Todos os status</option><option value="active">Ativa</option><option value="completed">Concluída</option><option value="expired">Vencida</option><option value="canceled">Cancelada</option></select><input aria-label="Data inicial" type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} className={fieldClass} /><input aria-label="Data final" type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} className={fieldClass} /></div></section>
    {isError ? <div role="alert" className="rounded-2xl border border-red-100 bg-white p-10 text-center dark:border-red-500/15 dark:bg-[#1a1d27]"><p className="font-bold">Não foi possível carregar as metas.</p><button type="button" onClick={() => refetch()} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-cyan-700"><RefreshCw className="h-4 w-4" />Tentar novamente</button></div> : <><div className="hidden md:block"><DataTable columns={columns} data={goals} isLoading={isLoading} emptyTitle="Nenhuma meta encontrada." emptySubtitle="Crie uma meta ou ajuste os filtros do período." /></div><div className="grid grid-cols-1 gap-3 md:hidden">{isLoading ? Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-56 animate-pulse rounded-2xl bg-gray-100 dark:bg-white/5" />) : goals.map((goal) => <article key={goal.id} className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-gray-900 dark:text-white">{goal.name}</h2><p className="text-xs text-gray-500">{goal.employeeName || goal.teamName}</p></div><GoalStatusBadge status={goal.effectiveStatus} /></div><div className="mt-4"><GoalProgress value={goal.progressPercent} /></div><div className="mt-4 flex items-end justify-between"><p className="text-xs text-gray-500">{formatGoalValue(goal, goal.currentResult)} de <strong>{formatGoalValue(goal)}</strong></p>{actions(goal)}</div></article>)}</div></>}
    <GoalModal isOpen={isOpen} goal={editing} employees={employees} teams={teams} isLoading={isSaving} onClose={() => setIsOpen(false)} onSave={async (input) => { await saveGoal({ input, id: editing?.id }); setIsOpen(false); }} /><GoalResultModal goal={manualGoal} isLoading={isUpdatingResult} onClose={() => setManualGoal(undefined)} onSave={async (value) => { if (manualGoal) await updateResult({ id: manualGoal.id, value }); setManualGoal(undefined); }} />
  </div>;
};
