import { ArrowLeft, History, Loader2, Target, Users } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { PageHeader } from '@/components/shared/PageHeader';
import { useTeamDetails } from '@/hooks/usePeople';
import { AdministrativeNotice } from './components/AdministrativeNotice';
import { EmployeeAvatar, EmployeeStatusBadge, GoalProgress, GoalStatusBadge, TeamStatusBadge } from './components/PeoplePrimitives';
import { AUDIT_EVENT_LABELS, formatCurrency, formatGoalValue } from './peopleDomain';

const yearPeriod = () => { const year = new Date().getFullYear(); return { from: `${year}-01-01`, to: `${year}-12-31` }; };

export const TeamDetailPage = () => {
  const { id = '' } = useParams(); const navigate = useNavigate(); const period = yearPeriod();
  const { performance, employees, goals, audit } = useTeamDetails(id, period.from, period.to);
  const metrics = performance.data?.find((item) => item.team.id === id); const team = metrics?.team;
  if (performance.isLoading || employees.isLoading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-700" /></div>;
  if (!team) return <div role="alert" className="rounded-2xl border border-red-100 bg-white p-10 text-center dark:bg-[#1a1d27]"><h1 className="font-bold">Equipe não encontrada.</h1><button type="button" onClick={() => navigate('/pessoas/equipes')} className="mt-4 text-sm font-semibold text-cyan-700">Voltar para equipes</button></div>;
  return <div className="space-y-5 animate-fade-in"><button type="button" onClick={() => navigate('/pessoas/equipes')} className="inline-flex items-center gap-2 text-sm font-semibold text-gray-500 hover:text-cyan-700"><ArrowLeft className="h-4 w-4" />Equipes</button><PageHeader title={team.name} subtitle={team.description || 'Acompanhamento da equipe'} /><AdministrativeNotice />
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-gray-900 dark:text-white">Resumo do período</h2><TeamStatusBadge status={team.status} /></div><p className="mt-1 text-sm text-gray-500">Gestor: {team.managerName || 'Não informado'}</p></div><p className="text-sm font-semibold text-gray-700 dark:text-gray-200">{team.activeMembers} membros ativos</p></div><dl className="mt-5 grid grid-cols-2 gap-4 lg:grid-cols-5"><div><dt className="text-xs text-gray-400">Meta consolidada</dt><dd className="font-bold">{metrics.goalTarget ? formatCurrency(metrics.goalTarget) : 'Sem meta em valor'}</dd></div><div><dt className="text-xs text-gray-400">Resultado consolidado</dt><dd className="font-bold">{metrics.goalTarget ? formatCurrency(metrics.goalResult) : 'Não aplicável'}</dd></div><div><dt className="text-xs text-gray-400">Vendas reais</dt><dd className="font-bold">{metrics.hasSalesSource ? formatCurrency(metrics.salesTotal || 0) : 'Sem fonte compatível'}</dd></div><div><dt className="text-xs text-gray-400">Metas em risco</dt><dd className="font-bold">{metrics.goalsAtRisk}</dd></div><div><dt className="text-xs text-gray-400">Metas concluídas</dt><dd className="font-bold">{metrics.goalsCompleted}</dd></div></dl><div className="mt-5"><GoalProgress value={metrics.progressPercent} /></div></section>
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><h2 className="mb-4 flex items-center gap-2 font-bold text-gray-900 dark:text-white"><Users className="h-5 w-5 text-cyan-700" />Membros</h2>{employees.data?.length ? <div className="space-y-3">{employees.data.map((employee) => <button type="button" key={employee.id} onClick={() => navigate(`/pessoas/funcionarios/${employee.id}`)} className="flex w-full items-center gap-3 rounded-xl border border-gray-100 p-3 text-left hover:border-cyan-200 focus-visible:ring-2 focus-visible:ring-cyan-500 dark:border-white/5"><EmployeeAvatar name={employee.fullName} /><span className="flex-1"><strong className="block text-sm text-gray-900 dark:text-white">{employee.fullName}</strong><span className="text-xs text-gray-500">{employee.jobTitle}</span></span><EmployeeStatusBadge status={employee.status} /></button>)}</div> : <p className="py-8 text-center text-sm text-gray-500">Nenhum membro vinculado.</p>}</section><section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><h2 className="mb-4 flex items-center gap-2 font-bold text-gray-900 dark:text-white"><Target className="h-5 w-5 text-cyan-700" />Metas individuais e coletivas</h2>{goals.data?.length ? <div className="space-y-4">{goals.data.map((goal) => <article key={goal.id} className="rounded-xl border border-gray-100 p-3 dark:border-white/5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold text-gray-900 dark:text-white">{goal.name}</h3><p className="text-xs text-gray-500">{goal.employeeName || 'Meta coletiva'} · {formatGoalValue(goal, goal.currentResult)} de {formatGoalValue(goal)}</p></div><GoalStatusBadge status={goal.effectiveStatus} /></div><div className="mt-3"><GoalProgress value={goal.progressPercent} /></div></article>)}</div> : <p className="py-8 text-center text-sm text-gray-500">Nenhuma meta no período.</p>}</section></div>
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-white/5 dark:bg-[#1a1d27]"><h2 className="mb-4 flex items-center gap-2 font-bold text-gray-900 dark:text-white"><History className="h-5 w-5 text-cyan-700" />Histórico relevante</h2>{audit.data?.length ? <ol className="space-y-4">{audit.data.map((event) => <li key={event.id} className="border-l-2 border-cyan-100 pl-4 dark:border-cyan-400/20"><h3 className="text-sm font-semibold">{AUDIT_EVENT_LABELS[event.eventType] || event.eventType}</h3><p className="text-xs text-gray-500">{event.actorName} · {new Date(event.createdAt).toLocaleString('pt-BR')}</p></li>)}</ol> : <p className="py-8 text-center text-sm text-gray-500">Nenhum evento registrado.</p>}</section>
  </div>;
};
