import { X } from 'lucide-react';
import { Commission } from '@/types';
import { formatCurrency, formatReferencePeriod } from '../peopleDomain';
import { CommissionStatusBadge, FieldValue } from './PeoplePrimitives';

export const CommissionDetailsModal = ({ commission, onClose }: { commission?: Commission; onClose: () => void }) => {
  if (!commission) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="commission-details-title"><button type="button" aria-label="Fechar detalhes" className="fixed inset-0 bg-black/55 backdrop-blur-sm" onClick={onClose} /><div className="relative z-10 w-full max-w-lg rounded-2xl border border-gray-100 bg-white p-6 shadow-2xl dark:border-white/5 dark:bg-[#1a1d27]"><div className="mb-5 flex items-start justify-between border-b border-gray-100 pb-4 dark:border-white/5"><div><h2 id="commission-details-title" className="text-lg font-bold text-gray-900 dark:text-white">Detalhes da comissão</h2><p className="mt-1 text-xs text-gray-500">Registro administrativo informado manualmente.</p></div><button type="button" onClick={onClose} aria-label="Fechar" className="rounded-lg p-2 text-gray-400 hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-500 dark:hover:bg-white/5"><X className="h-5 w-5" /></button></div><dl className="grid grid-cols-1 gap-5 sm:grid-cols-2"><FieldValue label="Funcionário">{commission.employeeName}</FieldValue><FieldValue label="Status"><CommissionStatusBadge status={commission.status} /></FieldValue><FieldValue label="Descrição / origem">{commission.description}</FieldValue><FieldValue label="Período">{formatReferencePeriod(commission.referencePeriod)}</FieldValue><FieldValue label="Valor informado">{formatCurrency(commission.grossAmount)}</FieldValue><FieldValue label="Responsável">{commission.createdByName}</FieldValue><div className="sm:col-span-2"><FieldValue label="Observações internas">{commission.internalNotes}</FieldValue></div></dl></div></div>;
};
