import React, { useEffect, useState } from 'react';
import { AlertCircle, Check, Copy, Globe2, History, Loader2, Mail, RefreshCw, Send, ShieldCheck, Unplug } from 'lucide-react';
import { toast } from 'sonner';
import { ConfirmModal } from '../../../components/shared/ConfirmModal';
import { useEmailSender } from '../../../hooks/useEmailSender';
import type { EmailConnection, EmailDomain, EmailSenderStatus } from '../../../services/emailSenderService';

const card = 'bg-white dark:bg-[#1a1d27] border border-gray-100 dark:border-white/5 rounded-2xl shadow-sm p-6';
const input = 'w-full px-4 py-2.5 border border-gray-200 dark:border-white/10 rounded-xl bg-white dark:bg-white/5 text-sm text-gray-900 dark:text-white outline-none focus:ring-2 focus:ring-[#10b981] disabled:opacity-60';
const primary = 'inline-flex items-center justify-center gap-2 rounded-xl bg-[#10b981] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#059669] disabled:cursor-not-allowed disabled:opacity-60';
const secondary = 'inline-flex items-center justify-center gap-2 rounded-xl border border-gray-200 dark:border-white/10 px-4 py-2.5 text-sm font-semibold text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-white/5 disabled:opacity-60';

const labels = { active: 'Ativo', pending: 'Pendente', expired: 'Expirado', error: 'Erro', disconnected: 'Desconectado', verified: 'Verificado', failed: 'Falhou', revoked: 'Revogado' } as const;
type BadgeStatus = keyof typeof labels;
const StatusBadge: React.FC<{ status: BadgeStatus }> = ({ status }) => {
  const color = status === 'active' || status === 'verified' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-400' : status === 'pending' ? 'bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-400' : 'bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-400';
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${color}`}>{labels[status]}</span>;
};

const DomainCard: React.FC<{ domain: EmailDomain; canConfigure: boolean; busy: boolean; onVerify: () => Promise<unknown>; onSelect: (senderEmail: string) => Promise<unknown> }> = ({ domain, canConfigure, busy, onVerify, onSelect }) => {
  const [senderEmail, setSenderEmail] = useState(`contato@${domain.domain}`);
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); toast.success('Registro copiado.'); };
  return <div className="rounded-2xl border border-gray-100 dark:border-white/5 p-4 space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-gray-900 dark:text-white">{domain.domain}</p>{domain.status === 'verified' && <p className="text-xs font-medium text-emerald-600">Método recomendado</p>}{domain.lastCheckedAt && <p className="text-xs text-gray-500">Verificado em {new Date(domain.lastCheckedAt).toLocaleString('pt-BR')}</p>}</div><StatusBadge status={domain.status} /></div>
    {domain.records.length > 0 && <div className="overflow-x-auto rounded-xl border border-gray-100 dark:border-white/5"><table className="min-w-full text-xs"><thead className="bg-gray-50 dark:bg-white/[0.03] text-left text-gray-500"><tr><th className="p-3">Tipo</th><th className="p-3">Host</th><th className="p-3">Valor</th><th className="p-3">Status</th><th className="p-3" /></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-white/5">{domain.records.map((record) => <tr key={record.id}><td className="p-3 font-medium text-gray-700 dark:text-gray-200">{record.recordType}</td><td className="p-3 font-mono text-gray-500">{record.host}</td><td className="p-3 font-mono text-gray-500 max-w-[280px] truncate" title={record.value}>{record.value}</td><td className="p-3"><StatusBadge status={record.status as BadgeStatus} /></td><td className="p-3"><button type="button" aria-label="Copiar registro" onClick={() => copy(record.value)} className="text-gray-400 hover:text-emerald-600"><Copy className="w-4 h-4" /></button></td></tr>)}</tbody></table></div>}
    {canConfigure && <div className="flex flex-col sm:flex-row gap-2"><button type="button" onClick={() => { void onVerify().catch(() => undefined); }} disabled={busy} className={secondary}><RefreshCw className="w-4 h-4" /> Verificar DNS</button>{domain.status === 'verified' && <><input aria-label={`Remetente do domínio ${domain.domain}`} value={senderEmail} onChange={(event) => setSenderEmail(event.target.value)} className={input} /><button type="button" onClick={() => { void onSelect(senderEmail).catch(() => undefined); }} disabled={busy} className={primary}><Check className="w-4 h-4" /> Usar domínio</button></>}</div>}
  </div>;
};

export const EmailSendingTab: React.FC = () => {
  const email = useEmailSender();
  const [displayName, setDisplayName] = useState('SobControle');
  const [replyTo, setReplyTo] = useState('');
  const [testRateLimitPerHour, setTestRateLimitPerHour] = useState(20);
  const [newDomain, setNewDomain] = useState('');
  const [testRecipient, setTestRecipient] = useState('');
  const [testIntentKey, setTestIntentKey] = useState(() => `test:${crypto.randomUUID()}`);
  const [disconnectTarget, setDisconnectTarget] = useState<EmailConnection>();
  useEffect(() => { if (email.state) { setDisplayName(email.state.settings.displayName); setReplyTo(email.state.settings.replyToEmail || ''); setTestRateLimitPerHour(email.state.settings.testRateLimitPerHour); } }, [email.state]);
  if (email.isLoading) return <div className={`${card} flex justify-center py-20`}><Loader2 className="w-6 h-6 animate-spin text-emerald-500" /></div>;
  if (!email.state || email.error) return <div className={card}><div className="flex items-center gap-3 text-red-600"><AlertCircle className="w-5 h-5" /><p>Não foi possível carregar a configuração de envio.</p></div><button type="button" onClick={() => email.refetch()} className={`${secondary} mt-4`}>Tentar novamente</button></div>;
  const { settings, permissions, connections, domains, history } = email.state;
  const currentLabel = settings.mode === 'platform' ? 'Remetente padrão SobControle' : settings.mode === 'verified_domain' ? 'Domínio verificado' : settings.mode === 'google_oauth' ? 'Google Workspace' : 'Microsoft 365';
  const currentStatus: BadgeStatus = settings.mode === 'verified_domain'
    ? (domains.find((domain) => domain.id === settings.selectedDomainId)?.status || 'pending')
    : settings.mode === 'google_oauth' || settings.mode === 'microsoft_oauth'
      ? (connections.find((connection) => connection.id === settings.selectedConnectionId)?.status || 'expired')
      : 'active';

  return <div className="space-y-6">
    <section className={card}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><span className="p-2 rounded-xl bg-emerald-50 text-emerald-600 dark:bg-emerald-950/30"><Mail className="w-5 h-5" /></span><div><h2 className="text-lg font-bold text-gray-900 dark:text-white">Envio de e-mails</h2><p className="text-sm text-gray-500">Configure o remetente transacional desta empresa.</p></div></div><StatusBadge status={currentStatus} /></div><div className="mt-5 rounded-2xl bg-gray-50 dark:bg-white/[0.03] p-4"><p className="text-xs uppercase tracking-wide text-gray-500">Remetente atual</p><p className="mt-1 font-semibold text-gray-900 dark:text-white">{currentLabel}</p><p className="text-sm text-gray-500">{settings.displayName} &lt;{settings.senderEmail || 'não configurado'}&gt;</p><p className="mt-1 text-xs text-gray-400">Último envio: {settings.lastSentAt ? new Date(settings.lastSentAt).toLocaleString('pt-BR') : 'nenhum envio registrado'}</p></div>{!permissions.canConfigure && <div className="mt-4 flex gap-2 rounded-xl bg-blue-50 p-3 text-sm text-blue-700 dark:bg-blue-950/30 dark:text-blue-300"><ShieldCheck className="w-5 h-5 shrink-0" /> Você pode consultar e enviar testes. Somente administradores alteram o remetente.</div>}</section>

    {permissions.canConfigure && <section className={card}><h3 className="font-bold text-gray-900 dark:text-white">Identidade e método de envio</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="space-y-1"><span className="text-xs font-semibold text-gray-500">Nome exibido</span><input value={displayName} onChange={(event) => setDisplayName(event.target.value)} className={input} maxLength={120} /></label><label className="space-y-1"><span className="text-xs font-semibold text-gray-500">Responder para (opcional)</span><input type="email" value={replyTo} onChange={(event) => setReplyTo(event.target.value)} className={input} /></label></div><label className="mt-4 block max-w-xs space-y-1"><span className="text-xs font-semibold text-gray-500">Limite de testes por hora (empresa)</span><input type="number" min={1} max={100} value={testRateLimitPerHour} onChange={(event) => setTestRateLimitPerHour(Number(event.target.value))} className={input} /></label><div className="mt-5 grid gap-3 md:grid-cols-3">
      <button type="button" disabled={email.isSaving} onClick={() => { void email.savePlatform({ displayName, replyTo, testRateLimitPerHour }).catch(() => undefined); }} className="rounded-2xl border border-gray-100 dark:border-white/5 p-4 text-left hover:border-emerald-300"><Mail className="w-5 h-5 text-emerald-600" /><span className="mt-3 block font-semibold text-gray-900 dark:text-white">SobControle</span><span className="text-xs text-gray-500">Remetente padrão gerenciado</span></button>
      <button type="button" disabled={email.isSaving} onClick={() => { void email.startOAuth('google').catch(() => undefined); }} className="rounded-2xl border border-gray-100 dark:border-white/5 p-4 text-left hover:border-emerald-300"><span className="text-lg font-bold text-blue-600">G</span><span className="mt-3 block font-semibold text-gray-900 dark:text-white">Google Workspace</span><span className="text-xs text-gray-500">OAuth com escopo apenas de envio</span></button>
      <button type="button" disabled={email.isSaving} onClick={() => { void email.startOAuth('microsoft').catch(() => undefined); }} className="rounded-2xl border border-gray-100 dark:border-white/5 p-4 text-left hover:border-emerald-300"><span className="text-lg font-bold text-sky-600">M</span><span className="mt-3 block font-semibold text-gray-900 dark:text-white">Microsoft 365</span><span className="text-xs text-gray-500">OAuth com Mail.Send</span></button>
    </div>{connections.length > 0 && <div className="mt-4 space-y-2">{connections.map((connection) => <div key={connection.id} className="flex items-center justify-between gap-3 rounded-xl border border-gray-100 dark:border-white/5 p-3"><div><p className="text-sm font-semibold text-gray-900 dark:text-white">{connection.accountEmail}</p><p className="text-xs capitalize text-gray-500">{connection.provider}</p></div><div className="flex items-center gap-2"><StatusBadge status={connection.status as EmailSenderStatus} /><button type="button" aria-label={`Desconectar ${connection.accountEmail}`} onClick={() => setDisconnectTarget(connection)} className="p-2 text-gray-400 hover:text-red-500"><Unplug className="w-4 h-4" /></button></div></div>)}</div>}</section>}

    <section className={card}><div className="flex items-center gap-3"><Globe2 className="w-5 h-5 text-emerald-600" /><div><h3 className="font-bold text-gray-900 dark:text-white">Domínio próprio</h3><p className="text-sm text-gray-500">O envio só é liberado depois da verificação DNS. Recomendamos publicar também uma política DMARC.</p></div></div>{permissions.canConfigure && <div className="mt-4 flex flex-col sm:flex-row gap-2"><input aria-label="Novo domínio de envio" value={newDomain} onChange={(event) => setNewDomain(event.target.value)} placeholder="empresa.com.br" className={input} /><button type="button" disabled={email.isSaving || !newDomain.trim()} onClick={() => { void email.createDomain(newDomain).then(() => setNewDomain('')).catch(() => undefined); }} className={primary}>Adicionar domínio</button></div>}<div className="mt-4 space-y-3">{domains.length ? domains.map((domain) => <DomainCard key={domain.id} domain={domain} canConfigure={permissions.canConfigure} busy={email.isSaving} onVerify={() => email.verifyDomain(domain.id)} onSelect={(senderEmail) => email.saveDomainSender({ domainId: domain.id, displayName, senderEmail, replyTo, testRateLimitPerHour })} />) : <p className="rounded-xl border border-dashed border-gray-200 dark:border-white/10 p-6 text-center text-sm text-gray-500">Nenhum domínio cadastrado.</p>}</div></section>

    <section className={card}><div className="flex items-center gap-3"><Send className="w-5 h-5 text-emerald-600" /><div><h3 className="font-bold text-gray-900 dark:text-white">Enviar teste</h3><p className="text-sm text-gray-500">Mensagem fixa, sem dados do negócio ou conteúdo livre.</p></div></div><div className="mt-4 flex flex-col sm:flex-row gap-2"><label className="sr-only" htmlFor="email-test-recipient">Destinatário do teste</label><input id="email-test-recipient" type="email" value={testRecipient} onChange={(event) => { setTestRecipient(event.target.value); setTestIntentKey(`test:${crypto.randomUUID()}`); }} placeholder="destinatario@empresa.com" className={input} /><button type="button" disabled={email.isTesting || !testRecipient.trim()} onClick={() => { void email.sendTest({ recipient: testRecipient, idempotencyKey: testIntentKey }).then((result) => { if (result.status === 'sent' || result.status === 'delivered') setTestIntentKey(`test:${crypto.randomUUID()}`); }).catch(() => undefined); }} className={primary}>{email.isTesting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />} Enviar teste</button></div></section>

    <section className={card}><div className="flex items-center gap-3"><History className="w-5 h-5 text-emerald-600" /><div><h3 className="font-bold text-gray-900 dark:text-white">Histórico recente</h3><p className="text-sm text-gray-500">Destinatários mascarados e erros sanitizados.</p></div></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b border-gray-100 dark:border-white/5 text-left text-xs text-gray-500"><tr><th className="py-3 pr-4">Data</th><th className="py-3 pr-4">Destinatário</th><th className="py-3 pr-4">Origem</th><th className="py-3 pr-4">Provedor</th><th className="py-3">Status</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-white/5">{history.map((item) => <tr key={item.id}><td className="py-3 pr-4 whitespace-nowrap text-gray-500">{new Date(item.createdAt).toLocaleString('pt-BR')}</td><td className="py-3 pr-4 font-mono text-gray-600 dark:text-gray-300">{item.recipientMasked}</td><td className="py-3 pr-4 text-gray-500">{item.origin}</td><td className="py-3 pr-4 capitalize text-gray-500">{item.provider}</td><td className="py-3"><StatusBadge status={item.status === 'sent' || item.status === 'delivered' ? 'active' : item.status === 'queued' || item.status === 'sending' ? 'pending' : 'failed'} /></td></tr>)}</tbody></table>{history.length === 0 && <p className="py-8 text-center text-sm text-gray-500">Nenhum envio registrado.</p>}</div></section>
    <ConfirmModal isOpen={Boolean(disconnectTarget)} title="Desconectar remetente" message={`Desconectar ${disconnectTarget?.accountEmail || 'esta conta'}? Os tokens armazenados serão excluídos e o remetente voltará ao padrão.`} confirmText="Desconectar" isLoading={email.isSaving} onCancel={() => setDisconnectTarget(undefined)} onConfirm={async () => { if (!disconnectTarget) return; try { await email.disconnect(disconnectTarget.id); setDisconnectTarget(undefined); } catch { /* Toast handled by the mutation. */ } }} />
  </div>;
};
