DROP FUNCTION IF EXISTS public.get_team_sales_totals(DATE, DATE);
DROP FUNCTION IF EXISTS public.get_sales_goal_progress();
DROP FUNCTION IF EXISTS public.set_sales_goal_status(UUID, TEXT);
DROP FUNCTION IF EXISTS public.update_sales_goal_result(UUID, NUMERIC);
DROP FUNCTION IF EXISTS public.save_sales_goal(UUID, TEXT, TEXT, TEXT, UUID, UUID, TEXT, NUMERIC, DATE, DATE, TEXT);
DROP FUNCTION IF EXISTS public.save_team(UUID, TEXT, TEXT, UUID, TEXT);
DROP FUNCTION IF EXISTS public.set_team_status(UUID, TEXT);
DROP TRIGGER IF EXISTS sales_goals_write_audit_event ON public.sales_goals;
DROP TRIGGER IF EXISTS teams_write_audit_event ON public.teams;
DROP FUNCTION IF EXISTS public.people_write_goal_audit_event();
DROP FUNCTION IF EXISTS public.people_write_team_audit_event();
DROP TABLE IF EXISTS public.sales_goals;
ALTER TABLE public.people_audit_events DROP COLUMN IF EXISTS team_id;
ALTER TABLE public.commissions DROP CONSTRAINT IF EXISTS commissions_team_company_fk;
ALTER TABLE public.commissions DROP COLUMN IF EXISTS team_id;
ALTER TABLE public.teams DROP CONSTRAINT IF EXISTS teams_manager_company_fk;
ALTER TABLE public.employees DROP CONSTRAINT IF EXISTS employees_team_company_fk;
ALTER TABLE public.employees DROP CONSTRAINT IF EXISTS employees_manager_company_fk;
ALTER TABLE public.employees DROP COLUMN IF EXISTS team_id;
ALTER TABLE public.employees DROP COLUMN IF EXISTS manager_employee_id;
ALTER TABLE public.employees DROP COLUMN IF EXISTS sales_profile_id;
DROP TABLE IF EXISTS public.teams;
